#!/bin/bash
#
# Cleans up containers and images for one or more services.
# Usage:
# app-clean - Removes the containers and the images for all services.
# app-clean my_service - Removes the container and the image for service `my_service`

source /usr/local/bin/app-env-build

if [ $# -eq 0 ]; then
    requested_service=""
else
    requested_service=$1
fi

for service in ${APP_CONTAINER_SERVICES_ARRAY[*]}
do
    clean=false
    if [ -z "${requested_service}" ]; then
        clean=true
    elif [ "${service}" == "${requested_service}" ]; then
        clean=true
    fi

    if [[ "${clean}" = false ]]; then
        continue
    fi

    container=${APP_CONTAINER_POD_NAME}_${service}
    p container exists $container
    if [ $? -eq 0 ]; then
        echo "Removing container $container"
        p rm $container
    fi

    image=${APP_CONTAINER_REGISTRY}/${APP_CONTAINER_POD_NAME}_$service
    p image exists "$image"
    if [ $? -eq 0 ]; then
        echo "Removing image $container"
        b rmi "$image"
    fi
done
