#!/bin/bash
#
# Starts services.

source /usr/local/bin/app-env-build

# Create a pod that will hold contain all services.
#
# @I Support starting specific services and not others
#    type     : feature
#    priority : normal
#    labels   : service
#
# @I Support dependent services
#    type     : feature
#    priority : normal
#    labels   : service
echo "Creating the pod ..."
POD_COMMAND="p pod create --replace --name ${APP_CONTAINER_POD_NAME}"
for port in ${APP_CONTAINER_PORTS_ARRAY[*]}
do
    POD_COMMAND="${POD_COMMAND} --publish $port"
done

# Add the pod to any requested networks.
for network in ${APP_CONTAINER_NETWORKS_ARRAY[*]}
do
    # Create the network first if it doesn't exist.
    p network exists $network
    if [ $? -eq 1 ]
    then
        p network create $network
    fi

    POD_COMMAND="${POD_COMMAND} --network $network"
done

if [ ! -v ${APP_CONTAINER_HOSTNAME+x} ]; then
    POD_COMMAND="${POD_COMMAND} --hostname ${APP_CONTAINER_HOSTNAME}"
fi
eval ${POD_COMMAND}

# Run services.
for service in ${APP_CONTAINER_SERVICES_ARRAY[*]}
do
    # Get the buildahfile path so that we can pass it to the build script.
    # The `up` script can then determine if we are running from a locally built
    # or a remote image.
    buildahfile=
    if [ -f $PWD/podman/services/$service/buildahfile ]; then
        buildahfile=$PWD/podman/services/$service/buildahfile
    elif [ -f $PWD/podman/$service.buildahfile ]; then
        buildahfile=$PWD/podman/$service.buildahfile
    elif [ -f /etc/app-pod/conf.d/services/default/$service.buildahfile ]; then
        buildahfile=/etc/app-pod/conf.d/services/default/$service.buildahfile
    fi

    # We first check if we have a folder dedicated to the service.
    if [ -f $PWD/podman/services/$service/up.sh ]; then
        echo "Starting service '$service' from custom start script"
        source $PWD/podman/services/$service/up.sh $service "$buildahfile"

    # Otherwise we look for file in the general podman folder.
    elif [ -f $PWD/podman/$service.up.sh ]; then
        echo "Starting service '$service' from custom start script"
        source $PWD/podman/$service.up.sh $service "$buildahfile"

    # If dedicated service files do not exist, it must be one of the supported
    # services.
    else
        echo "Starting service '$service' from default start script"
        source /etc/app-pod/conf.d/services/default/$service.up.sh $service "$buildahfile"
    fi
done
exit
