#!/bin/bash
#
# Starts services.

source /usr/local/bin/app-env-build

# Run the pre-up script, if it exists.
if [ -f $PWD/podman/pre-up.sh ]; then
    echo "Running pre-up script ..."
    source $PWD/podman/pre-up.sh
fi

# Create a pod that will hold contain all services.
#
# @I Support dependent services
#    type     : feature
#    priority : normal
#    labels   : service
p pod exists ${APP_CONTAINER_POD_NAME}
if [ $? -eq 0 ]; then
    echo "Pod already exists"
else
    echo "Creating the pod ..."
    POD_COMMAND="p pod create --replace --name ${APP_CONTAINER_POD_NAME}"

    # Expose any requested ports.
    for port in ${APP_CONTAINER_PORTS_ARRAY[*]}
    do
        POD_COMMAND="${POD_COMMAND} --publish $port"
    done

    # Add the pod to any requested networks.
    for network in ${APP_CONTAINER_NETWORKS_ARRAY[*]}
    do
        # Create the network first if it doesn't exist.
        p network exists $network
        if [ $? -eq 1 ]
        then
            p network create $network
        fi

        POD_COMMAND="${POD_COMMAND} --network $network"
    done

    if [ ! -v ${APP_CONTAINER_HOSTNAME+x} ]; then
        POD_COMMAND="${POD_COMMAND} --hostname ${APP_CONTAINER_HOSTNAME}"
    fi
    eval ${POD_COMMAND}
fi

if [ $# -eq 0 ]; then
    requested_service=""
else
    requested_service=$1
fi

# Run services.
for service in ${APP_CONTAINER_SERVICES_ARRAY[*]}
do
    run=false
    if [ -z "${requested_service}" ]; then
        run=true
    elif [ "${service}" == "${requested_service}" ]; then
        run=true
    fi

    if [[ "${run}" = false ]]; then
        continue
    fi

    # Get the buildahfile path so that we can pass it to the build script.
    # The `up` script can then determine if we are running from a locally built
    # or a remote image.
    buildahfile=
    if [ -f $PWD/podman/services/$service/buildahfile ]; then
        buildahfile=$PWD/podman/services/$service/buildahfile
    elif [ -f $PWD/podman/$service.buildahfile ]; then
        buildahfile=$PWD/podman/$service.buildahfile
    elif [ -f /etc/app-pod/conf.d/services/default/$service.buildahfile ]; then
        buildahfile=/etc/app-pod/conf.d/services/default/$service.buildahfile
    fi

    read -r -d '' run_command << COMMAND
p run
  --detach
  --pod ${APP_CONTAINER_POD_NAME}
  --name ${APP_CONTAINER_POD_NAME}_$service
  --replace
COMMAND

    # Add environment variables to the service. Variables need to be prefixed
    # with "APP_CONTAINER_", followed by the capitalized service ID, then
    # "_ENV", then double underscore "__", and then the name of the environment
    # variable.
    # @I Support base64-encoded variables
    #    type     : improvement
    #    priority : low
    #    labels   : environment
    #    notes    : This is to support variables that cannot be parsed, such as
    #               private RSA keys. The encoded value should be added at
    #               `.env`, prefixed by `base64:`. We should then do the
    #               decoding it here.
    # @I Support loading variable value from file
    #    type     : improvement
    #    priority : low
    #    labels   : environment
    #    notes    : This is to support variables that cannot be parsed, such as
    #               private RSA keys. The value of the variable should be the
    #               absolute or relative path to the file that contains the
    #               value, prefixed by `file:`.
    variable_name_prefix="APP_CONTAINER_${service^^}_ENV__"
    variables=$(compgen -A variable | grep -E "^$variable_name_prefix.*")

    for variable in ${variables[*]}
    do
        variable_name=${variable#"$variable_name_prefix"}
        variable_value="${variable}"
        run_command="${run_command} --env ${variable_name}=${!variable_value}"
    done

    # We first check if we have a folder dedicated to the service.
    if [ -f $PWD/podman/services/$service/up.sh ]; then
        echo "Starting service '$service' from custom start script"
        source $PWD/podman/services/$service/up.sh $service "$buildahfile" "$run_command"

    # Otherwise we look for file in the general podman folder.
    elif [ -f $PWD/podman/$service.up.sh ]; then
        echo "Starting service '$service' from custom start script"
        source $PWD/podman/$service.up.sh $service "$buildahfile" "$run_command"

    # If dedicated service files do not exist, it must be one of the supported
    # services.
    else
        echo "Starting service '$service' from default start script"
        source /etc/app-pod/conf.d/services/default/$service.up.sh $service "$buildahfile" "$run_command"
    fi
done

# Run the post-up script, if it exists.
if [ -f $PWD/podman/post-up.sh ]; then
    echo "Running post-up script ..."
    source $PWD/podman/post-up.sh
fi
