#!/bin/bash
#
# Prepares environment for other scripts.
# 1. Loads the environment variables from the project definition.
# 2. Prepares any derivative environment variables expected by other scripts.

shopt -s expand_aliases
source ~/.bashrc.d/aliases.sh

if [ ! -f $PWD/.env ]; then
    echo 'No .env environment variable file found for the project.'
    exit
fi
export $(grep -v '^#' $PWD/.env | xargs)

# Require strict variable naming; an error will be thrown if the script
# references undefined variables.
set -u

# Detect ports.
if [ -z ${APP_CONTAINER_PORTS+x} ]; then
    APP_CONTAINER_PORTS=''
fi
IFS=',' read -r -a APP_CONTAINER_PORTS_ARRAY <<< "${APP_CONTAINER_PORTS}"

# Detect networks.
if [ -z ${APP_CONTAINER_NETWORKS+x} ]; then
    APP_CONTAINER_NETWORKS=''
fi
IFS=',' read -r -a APP_CONTAINER_NETWORKS_ARRAY <<< "${APP_CONTAINER_NETWORKS}"

# Detect and validate services.
# Service validation consists to checking whether the service is supported
# out-of-the-box, or if it has a custom definition.
#
# @I Make supported services configurable
#    type     : feature
#    priority : normal
#    labels   : config, service
#    notes    : Service definitions/scripts should be loaded from a
#               configuration folder e.g. `etc/app-pod/conf.d/services`.
#
# @I Support service packages e.g. `drupal-pods` etc.
#    type     : feature
#    priority : normal
#    labels   : config, service
#    notes    : 1. Service definitions via environment variables would define
#                  the package as there could be multiple packages defining a
#                  service with the same name.
#               2. Service packages should be installable i.e. provide a script
#                  that copies the package, upon installation or later, to the
#                  right location.
#               3. Each package should have basic information defined in a YAML
#                  file e.g. name, supported services, update URL etc.
IFS=',' read -r -a APP_CONTAINER_SERVICES_ARRAY <<< "${APP_CONTAINER_SERVICES}"

# Load supported services from a file, removing empty and commented out lines.
supported_services_filepath="/etc/app-pod/conf.d/services/default/list"
mapfile -t SUPPORTED_SERVICES_ARRAY < <(grep -vE '^(\s*#|\s*$)' "${supported_services_filepath}")

for service in ${APP_CONTAINER_SERVICES_ARRAY[*]}
do
    supported=false
    if [[ "${SUPPORTED_SERVICES_ARRAY[@]}" =~ "$service" ]]; then
        supported=true

    elif [ -f $PWD/podman/$service.up.sh ]; then
        supported=true
    fi

    if [[ "$supported" = false ]]; then
        printf "Service '"$service"' is not supported and no custom definition was found\n"
        exit 1
    fi

    # Load default variables defined by services.
    service_variables_filepath="/etc/app-pod/conf.d/services/default/${service}.env"
    if [ -f "${service_variables_filepath}" ]; then
        while read service_variable; do
            IFS='=' read -r service_variable_name service_variable_value <<< "${service_variable}"
            # Load the variable only if no override has been defined.
            # The overrides would have been loaded at the top of this file from
            # the project's `.env` file.
            if [ -z ${!service_variable_name+x} ]; then
                export ${service_variable}
            fi
        done < "${service_variables_filepath}"
    fi
done

# Prepare derivative environment variables.
# @I Support custom container name defined in environment variables
#    type     : improvement
#    priority : normal
#    labels   : container, environment

# Compatibility, should remove support for "X_APP_GROUP/PROJECT/ENV".
if [ -z ${APP_CONTAINER_GROUP+x} ]; then
    APP_CONTAINER_GROUP="${APP_GROUP}"
fi
if [ -z ${APP_CONTAINER_PROJECT+x} ]; then
    APP_CONTAINER_PROJECT="${APP_PROJECT}"
fi
if [ -z ${APP_CONTAINER_ENVIRONMENT+x} ]; then
    APP_CONTAINER_ENVIRONMENT="${APP_ENV}"
fi
APP_CONTAINER_VOLUMES_DIR=${PODMAN_VOLUMES_DIR}/${APP_CONTAINER_VOLUMES_SUBPATH}
if [ -z ${APP_CONTAINER_NAME+x} ]; then
    APP_CONTAINER_NAME=${APP_CONTAINER_GROUP}_${APP_CONTAINER_PROJECT}_${APP_CONTAINER_ENVIRONMENT}
fi
APP_CONTAINER_POD_NAME="${APP_CONTAINER_NAME}"
APP_IDE_HOME=${PODMAN_VOLUMES_DIR}/apps/ide

if [ ! -d "${APP_CONTAINER_VOLUMES_DIR}" ]; then
    mkdir -p ${APP_CONTAINER_VOLUMES_DIR}
fi
