#!/bin/bash

p run \
  --detach \
  --pod ${APP_CONTAINER_POD_NAME} \
  --name ${APP_CONTAINER_POD_NAME}_nextcloud \
  --env MYSQL_HOST=${APP_CONTAINER_NEXTCLOUD_MYSQL_HOST} \
  --env MYSQL_DATABASE=${APP_CONTAINER_NEXTCLOUD_MYSQL_DATABASE} \
  --env MYSQL_USER=${APP_CONTAINER_NEXTCLOUD_MYSQL_USER} \
  --env MYSQL_PASSWORD=${APP_CONTAINER_NEXTCLOUD_MYSQL_PASSWORD} \
  --env NEXTCLOUD_ADMIN_USER=${APP_CONTAINER_NEXTCLOUD_ADMIN_USER} \
  --env NEXTCLOUD_ADMIN_PASSWORD=${APP_CONTAINER_NEXTCLOUD_ADMIN_PASSWORD} \
  --volume ${APP_CONTAINER_VOLUMES_DIR}/config:/var/www/html/config \
  --volume ${APP_CONTAINER_VOLUMES_DIR}/data:/var/www/html/data \
  docker.io/library/nextcloud:${APP_CONTAINER_NEXTCLOUD_VERSION}
